### CREATE five documents.
POST http://localhost:3000/deliveryRobots HTTP/1.1
content-type: application/json

{
    "robotID": "Glide",
    "deliveryTime": "2023-12-10",
    "numberOfPackages": 10
}


### CREATE 2
POST http://localhost:3000/DeliveryRobots HTTP/1.1
content-type: application/json

{
    "robotID": "Atlas.exe",
    "deliveryTime": "2023-1-15",
    "numberOfPackages": 20
}

### CREATE 3
POST http://localhost:3000/DeliveryRobots HTTP/1.1
content-type: application/json

{
    "robotID": "DexterityMan",
    "deliveryTime": "2024-2-28",
    "numberOfPackages": 3
}

### CREATE 4
POST http://localhost:3000/DeliveryRobots HTTP/1.1
content-type: application/json

{
    "robotID": "BipedalBot",
    "deliveryTime": "2024-1-29",
    "numberOfPackages": 8
}

### CREATE 5
POST http://localhost:3000/DeliveryRobots HTTP/1.1
content-type: application/json

{
    "robotID": "SecurityColonel",
    "deliveryTime": "2022-2-1",
    "numberOfPackages": 1
}


### RETRIEVE all documents.
GET http://localhost:3000/DeliveryRobots HTTP/1.1



### RETRIEVE a document by its ID.
### Replace the following ID with one that exists in the collection.
GET http://localhost:3000/DeliveryRobots/65e0ee63cd8eb1e33ebd11f2 HTTP/1.1


### UPDATE one document's year, by ID.
### Replace the ID in the following request with one that exists
### and update the year:
PUT http://localhost:3000/DeliveryRobots/65e0eca2cd8eb1e33ebd11e1 HTTP/1.1
content-type: application/json

{
    "robotID": "SecurityColonel",
    "deliveryTime": "2024-2-29",
    "numberOfPackages": 105
}

### DELETE by ID (responds with nothing if successful):
DELETE http://localhost:3000/DeliveryRobots/65e0ee1bcd8eb1e33ebd11eb HTTP/1.1



### RETRIEVE all documents (responds with 4 or the original 5):
GET http://localhost:3000/DeliveryRobots HTTP/1.1

